FROM grafana/grafana:10.4.2

# Copy provisioning configurations
COPY ./infra/monitoring/grafana/provisioning/datasources /etc/grafana/provisioning/datasources
COPY ./infra/monitoring/grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards

# Use default Grafana entrypoint
